version: "3.9"
2
 
3
services:
4
  app:
5
    build:
6
      context: .
7
    ports:
8
      - "8000:8000"
9
    volumes:
10
      - ./app:/app
11
    command: >
12
      sh -c "python manage.py runserver 0.0.0.0:8000"